name: CI

on:
  pull_request:
    paths-ignore: ['*.md']
  push:
    branches: [master]
    paths-ignore: ['*.md']

jobs:
  test:
    name: Test (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4, 8.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-composer-
      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-source
      - name: Run PHPUnit tests and generate code coverage
        run: |
          composer analyse
          phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml
      - name: Upload code coverage results
        run: bash <(curl -s https://codecov.io/bash)
